import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from './providers';
import { TooltipProvider } from "@/components/ui/tooltip"
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Navbar } from "@/components/navbar"
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "@/components/ui/sonner"
import { getLogtoContext } from '@logto/next/server-actions';
import { logtoConfig } from './logto';
import { InfraProvider } from "@/context/session-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { claims } = await getLogtoContext(logtoConfig);
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark" // Сразу ставим темную по дефолту для CTF
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <InfraProvider>
            <TooltipProvider>
              <SidebarProvider defaultOpen={false} >
                <AppSidebar user={claims}/>
                <SidebarInset className="flex flex-col h-screen overflow-hidden">
                  <Navbar />
                  <main className="flex-1 overflow-y-auto relative bg-background">
                    {/* Убираем <div className="p-6"> отсюда, если хотим страницы "в край" */}
                    {children}
                  </main>
                  <Toaster />
                </SidebarInset>
              </SidebarProvider>
            </TooltipProvider>
            </InfraProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html >
  );
}
